# Based on the sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build Hugo site

on:
  # Build on all PRs
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent build per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.145.0
    steps:
      - name: Setup Go (for Hugo Modules)
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - name: Ensure LFS files are present
        run: |
          git lfs install --local
          git lfs pull
      - name: Vendor Hugo modules
        run: |
          hugo mod vendor
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: >
          hugo
          --minify
          --baseURL "${{ steps.pages.outputs.base_url }}/"
          -s "./"
          --themesDir "./themes"
          --logLevel info
      - name: Assert build output exists
        run: test -d public && echo "Found ./public"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
